version: '3'

services:
  cassandra:
    image: cassandra:3.11.7
    ports:
      - 7000:7000
      - 7199:7199
      - 9042:9042
      - 9160:9160
    environment:
      CASSANDRA_CLUSTER_NAME: cassandraex
    container_name: cassandra
  cqlsh:
    image: cassandra:3.11.7
    entrypoint: cqlsh cassandra
    volumes:
      - ./cassandra/schema.cql:/schema.cql

